# src/main/resources/application-docker.yml
opcua:
  config-management:
    persistence-path: /app/config/opcua-runtime.yml

spring:
  data:
    redis:
      host: redis
      port: 6379
  session:
    store-type: redis

kafka:
  bootstrap-servers: kafka:9092

influxdb:
  url: http://influxdb:8086
